theme: jekyll-theme-slate
title: Andrew Lackey's home page
description: For any employers looking for my school projects, feel free to request access by sending an email to andrewlackey@u.boisestate.edu. 
Due to Boise State University's policies I am unable to make previous classwork publicly available.

Have a good day! :)


