theme: jekyll-theme-slate
title: Andrew Lackey's home page
description: Simple website for whatever I want to use it for. 
I will probably use it as a self advertising webiste for employers to see my work. 

Have a good day! :)


